### ISSUE TITLE
TODO 13/05

### ISSUE THREAD

**Issue by arnaudambro** [SocialGouv/ozensemble#36]
- [ ] Page Sevrage à la fin des objectifs
- [x] changer le rappel selon figma + insérer dans mes objectifs
- [x]  calcul par verre de l'estimation de ma consommation
- [x] Revoir les gains gagnés depuis le début
- [x] revoir le calcul sur la semaine en cours (par rapport au lundi et pas les 7 derniers jours)
- [x] bloquer le calendrier + ? partout si on a pas encore fait les objectifs
- [x] virer total verres par semaine de la  légende du calendrier (pour l'instant)
- [x] un peu d'espaces entre les boutons des jours ou je ne bois pas d'alcool
- [x] réajuster le design de se fixer un objectif pour que ce soit vraiment très joli (alignement des textes)
- [x]  changer la phrases "verres par semaine" pour être plus explicite
- [x] désactiver le bouton "je finalise" si pas de choix de boisson dans l'estimation + pas de négatif (et donc désactiver le moins)
- [x] pas de verres négatifs dans l'objectif (et partout)
- [x] police du jour d'aujourd'hui dans le calendrier -> c'est dégueu
- [ ] graph par semaine dans mon suivi consos
- [ ] petits messages personnalisés dans le suivi aussi
- [ ] modifier la tab Santé
- [x] **Laure** page consumption -> retour au bon endroit
- [x] **Laure** page consumption -> je n'ai pas bu

**Comment by arnaudambro** [comment]
BUUUUG
je peux pas modifier le truc au dessus, je le remet ici

- [ ] Page Sevrage à la fin des objectifs
- [ ] changer le rappel selon figma + insérer dans mes objectifs
- [ ] **Laure** calcul par verre de l'estimation de ma consommation
- [ ] Revoir les gains gagnés depuis le début
- [ ] revoir le calcul sur la semaine en cours (par rapport au lundi et pas les 7 derniers jours)
- [ ] **Laure** bloquer le calendrier + ? partout si on a pas encore fait les objectifs
- [x] **Laure** virer total verres par semaine de la  légende du calendrier (pour l'instant)
- [ ] **Laure** un peu d'espaces entre les boutons des jours ou je ne bois pas d'alcool
- [ ] réajuster le design de se fixer un objectif pour que ce soit vraiment très joli (alignement des textes)
- [ ] **Laure** changer la phrases "verres par semaine" pour être plus explicite
- [x] désactiver le bouton "je finalise" si pas de choix de boisson dans l'estimation + pas de négatif (et donc désactiver le moins)
- [x] **Laure** pas de verres négatifs dans l'objectif (et partout)
- [x] police du jour d'aujourd'hui dans le calendrier -> c'est dégueu
- [ ] graph par semaine dans mon suivi consos
- [ ] petits messages personnalisés dans le suivi aussi
- [ ] modifier la tab Santé
